ratings:
  paths:
  - lib/**
  - "**.rb"
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
          mass_threshold: 30
exclude_paths:
  - spec/**/*
  - features/**/*
  - fixtures/**/*
