language: ruby
rvm:
  - ruby-head
  - 2.4.0
  - 2.3.1
  - 2.2.4
matrix:
  include:
    - env: SUPPORTED_MIDDLEMAN=~> 3.4.1
    - env: SUPPORTED_MIDDLEMAN=~> 4.2.1
  allow_failures:
    - rvm: ruby-head
    - env: SUPPORTED_MIDDLEMAN="~> 4.2.1"
script:
  - bundle exec rake
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gemspec: middleman-thumbnailer.gemspec
  on:
    tags: true
addons:
  code_climate:
  repo_token: $CODECLIMATE_TOKEN
